[package]
name = "rt890-flash"
version = "1.2.0"
edition = "2021"

[profile.dev]
overflow-checks = false

[profile.release]
lto = true
opt-level = "z"
strip = true

[dependencies]
serialport5 = "5.0.*"
