[package]
name = "rt890-flash"
version = "1.0.0"
edition = "2021"

[profile.dev]
overflow-checks = false

[profile.release]
lto = true
opt-level = "s"
strip = true

[dependencies]
nix = "0.23.2"
serialport5 = "5.0.*"
